"""
OCM tests — model validation, spec fixtures (Annex G15-G20), KVN/XML round-trips.

Replaces:
- test_models.py:TestOCM*, TestOCMHeader*, TestOCMMetadata*, TestOCMTopLevel, etc.
- OCM rows missing from test_spec_fixtures.py (g15-g19 all should now pass)
"""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

import pydantic
import pytest
from conftest import (
    CREATION_DATE,
    EPOCH,
    FIXTURES,
    assert_models_equal,
    assert_semantic_equal,
    make_ocm,
)

from ccsds_data_messages import OCM, read, write
from ccsds_data_messages.io.kvn.ocm_reader import KVNOCMReader
from ccsds_data_messages.io.kvn.ocm_writer import KVNOCMWriter
from ccsds_data_messages.models.values import TimeSystem

if TYPE_CHECKING:
    from pathlib import Path

_OCM_READER = KVNOCMReader()
_OCM_WRITER = KVNOCMWriter()

_OCM_KVN_SPEC_FIXTURES_PASSING = [
    "ocm_g15_minimal.kvn",
    "ocm_g16_characteristics.kvn",
    "ocm_g17_deployments.kvn",
    "ocm_g18_multi_traj.kvn",
    "ocm_g19_covariance_histories.kvn",
]
_OCM_KVN_SPEC_FIXTURES_WRITER_GAP: list[str] = []
_OCM_KVN_SPEC_FIXTURES = (
    _OCM_KVN_SPEC_FIXTURES_PASSING + _OCM_KVN_SPEC_FIXTURES_WRITER_GAP
)


# ---------------------------------------------------------------------------
# Model validation
# ---------------------------------------------------------------------------


class TestOCMHeader:
    def test_ocm_header_version_mandatory(self):
        # §7.9.1: CCSDS_OCM_VERS M
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(creation_date=CREATION_DATE, originator="TEST")

    def test_ocm_header_version_xy_pattern_required(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(ccsds_ocm_vers="3", creation_date=CREATION_DATE, originator="TEST")

    def test_ocm_header_creation_date_mandatory(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(ccsds_ocm_vers="3.0", originator="TEST")

    def test_ocm_header_originator_mandatory(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(ccsds_ocm_vers="3.0", creation_date=CREATION_DATE)

    def test_ocm_header_comment_empty_list_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(
                ccsds_ocm_vers="3.0",
                creation_date=CREATION_DATE,
                originator="TEST",
                comment=[],
            )

    def test_ocm_header_comment_accepted(self):
        h = OCM.Header(
            ccsds_ocm_vers="3.0",
            creation_date=CREATION_DATE,
            originator="TEST",
            comment=["OCM generated by mission planning system"],
        )
        assert h.comment == ["OCM generated by mission planning system"]

    def test_ocm_header_minimal_valid(self):
        h = OCM.Header(
            ccsds_ocm_vers="3.0", creation_date=CREATION_DATE, originator="TEST"
        )
        assert h.originator == "TEST"


class TestOCMMetadata:
    def test_ocm_metadata_time_system_defaults_to_utc(self):
        # TIME_SYSTEM defaults to UTC (not mandatory in model, but M in spec with UTC default)
        meta = OCM.Metadata(epoch_tzero=EPOCH)
        assert meta.time_system == TimeSystem.UTC

    def test_ocm_metadata_epoch_tzero_mandatory(self):
        # §6.2.2.2: EPOCH_TZERO M — no default
        with pytest.raises(pydantic.ValidationError):
            OCM.Metadata(time_system=TimeSystem.UTC)

    def test_ocm_metadata_time_system_utc_accepted(self):
        meta = OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
        assert meta.time_system == TimeSystem.UTC

    def test_ocm_metadata_epoch_tzero_calendar_format_accepted(self):
        meta = OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero="2020-01-01T00:00:00")
        assert meta.epoch_tzero is not None

    def test_ocm_metadata_epoch_tzero_doy_format_accepted(self):
        meta = OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero="2020-001T00:00:00")
        assert meta.epoch_tzero is not None

    def test_ocm_metadata_julian_date_epoch_tzero_rejected(self):
        # §7.5.10: Julian Date withdrawn in v3
        with pytest.raises(pydantic.ValidationError):
            OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero="2459945.5")

    def test_ocm_metadata_optional_fields_default_none(self):
        meta = OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
        assert meta.object_name is None
        assert meta.international_designator is None

    def test_ocm_metadata_object_name_accepted(self):
        meta = OCM.Metadata(
            time_system=TimeSystem.UTC, epoch_tzero=EPOCH, object_name="TESTSAT"
        )
        assert meta.object_name == "TESTSAT"


class TestOCMTopLevel:
    def test_ocm_minimal_construction(self):
        ocm = make_ocm()
        assert ocm.header.ccsds_ocm_vers == "3.0"
        assert ocm.metadata.time_system == TimeSystem.UTC

    def test_ocm_with_trajectory_block(self):
        # OCM can have optional trajectory state time history blocks
        ocm = make_ocm()
        assert ocm.header.originator == "JAXA"

    def test_ocm_header_plus_metadata_only_accepted(self):
        # §6.2: header + metadata are the minimum; all data blocks are optional
        ocm = OCM(
            header=OCM.Header(
                ccsds_ocm_vers="3.0", creation_date=CREATION_DATE, originator="JAXA"
            ),
            metadata=OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH),
        )
        assert ocm.metadata.epoch_tzero is not None

    def test_ocm_header_version_3_5_accepted_as_valid_minor_increment(self):
        # §7.9.1: OCM supports any minor version under major 3
        h = OCM.Header(
            ccsds_ocm_vers="3.5", creation_date=CREATION_DATE, originator="TEST"
        )
        assert h.ccsds_ocm_vers == "3.5"

    def test_ocm_header_version_4_0_raises_non_3_major(self):
        # §7.9.1: OCM major version must be 3; '4.0' is not valid
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(
                ccsds_ocm_vers="4.0", creation_date=CREATION_DATE, originator="TEST"
            )

    def test_ocm_header_version_2_0_raises_non_3_major(self):
        # §7.9.1: OCM major version must be 3; '2.0' is not valid
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(
                ccsds_ocm_vers="2.0", creation_date=CREATION_DATE, originator="TEST"
            )


class TestOCMTrajectoryState:
    def test_ocm_trajectory_state_data_lines_strictly_increasing(self):
        # §6.2.2.5: time tags must be strictly increasing within a block
        with pytest.raises(pydantic.ValidationError):
            OCM.TrajectoryStateTimeHistory(
                traj_type="CARTPV",
                traj_id="PLAN_A",
                data_lines=[
                    "2020-001T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0",
                    "2020-001T00:00:00 6990.0 0.0 0.0 0.0 7.5 0.0",  # duplicate epoch
                ],
            )

    def test_ocm_trajectory_state_decreasing_time_raises(self):
        # §6.2.2.4: duplicate time tag forbidden
        with pytest.raises(pydantic.ValidationError):
            OCM.TrajectoryStateTimeHistory(
                traj_type="CARTPV",
                traj_id="PLAN_A",
                data_lines=[
                    "2020-001T00:10:00 7000.0 0.0 0.0 0.0 7.5 0.0",
                    "2020-001T00:00:00 6990.0 0.0 0.0 0.0 7.5 0.0",  # decreasing
                ],
            )

    def test_ocm_trajectory_state_single_data_line_accepted(self):
        # Single-line blocks are valid (no ordering constraint needed)
        block = OCM.TrajectoryStateTimeHistory(
            traj_type="CARTPV",
            traj_id="PLAN_A",
            data_lines=["2020-001T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0"],
        )
        assert len(block.data_lines) == 1

    def test_ocm_trajectory_state_increasing_time_accepted(self):
        block = OCM.TrajectoryStateTimeHistory(
            traj_type="CARTPV",
            traj_id="PLAN_A",
            data_lines=[
                "2020-001T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0",
                "2020-001T00:10:00 6990.0 0.0 0.0 0.0 7.5 0.0",
                "2020-001T00:20:00 6980.0 0.0 0.0 0.0 7.5 0.0",
            ],
        )
        assert len(block.data_lines) == 3

    def test_ocm_trajectory_empty_data_lines_raises(self):
        # §6.2.2.5: an empty data block has no meaning
        with pytest.raises(pydantic.ValidationError):
            OCM.TrajectoryStateTimeHistory(
                traj_type="CARTPV",
                traj_id="PLAN_A",
                data_lines=[],
            )


# ---------------------------------------------------------------------------
# OCMBuilder — one case per setter method
# ---------------------------------------------------------------------------


class TestOCMBuilder:
    def test_build_minimal(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .build()
        )
        assert ocm.header.originator == "JAXA"
        assert ocm.metadata.time_system == TimeSystem.UTC

    def test_build_with_trajectory_state(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .add_trajectory(
                traj_type="CARTPV",
                traj_id="PLAN_A",
                data_lines=["2020-001T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0"],
            )
            .build()
        )
        assert ocm.trajectory_states is not None
        assert ocm.trajectory_states[0].traj_id == "PLAN_A"

    def test_build_with_physical_characteristics(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .physical_characteristics(wet_mass=1000.0)
            .build()
        )
        assert ocm.physical_characteristics is not None
        assert ocm.physical_characteristics.wet_mass == 1000.0

    def test_build_with_covariance(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .add_covariance(
                cov_ref_frame="RSW",
                cov_type="CARTPV",
                cov_ordering="LTM",
                data_lines=["2020-001T00:00:00 1e-6"],
            )
            .build()
        )
        assert ocm.covariances is not None
        assert ocm.covariances[0].cov_ref_frame == "RSW"

    def test_build_with_maneuver(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .add_maneuver(
                man_id="M001",
                man_device_id="THR1",
                man_ref_frame="RSW",
                dc_type="CONTINUOUS",
                man_composition="TIME_ABSOLUTE,MAN_DURA,THR_X,THR_Y,THR_Z",
                data_lines=["2020-001T00:00:00 60.0 0.0 0.001 0.0"],
            )
            .build()
        )
        assert ocm.maneuvers is not None
        assert ocm.maneuvers[0].man_id == "M001"

    def test_build_with_perturbations_and_orbit_determination(self):
        # orbit_determination() requires a perturbations block to also be set.
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .perturbations(atmospheric_model="NRLMSISE00")
            .orbit_determination(
                od_id="OD1", od_method="RANGE", od_epoch="2020-001T00:00:00"
            )
            .build()
        )
        assert ocm.perturbations is not None
        assert ocm.orbit_determination is not None
        assert ocm.orbit_determination.od_id == "OD1"

    def test_build_with_user_defined(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .user_defined(EARTH_MODEL="WGS-84")
            .build()
        )
        assert ocm.user_defined is not None
        assert ocm.user_defined.user_defined["EARTH_MODEL"] == "WGS-84"

    def test_build_without_metadata_raises(self):
        with pytest.raises(ValueError):
            OCM.builder().header(originator="JAXA", creation_date=CREATION_DATE).build()


# ---------------------------------------------------------------------------
# Remaining OCM block types — direct-construction validation
# ---------------------------------------------------------------------------


class TestOCMSpaceObjectPhysicalCharacteristics:
    def test_all_fields_optional_empty_construction_accepted(self):
        phys = OCM.SpaceObjectPhysicalCharacteristics()
        assert phys.wet_mass is None

    def test_with_fields_accepted(self):
        phys = OCM.SpaceObjectPhysicalCharacteristics(wet_mass=1000.0, dry_mass=800.0)
        assert phys.wet_mass == 1000.0
        assert phys.dry_mass == 800.0


class TestOCMCovarianceTimeHistory:
    def test_empty_data_lines_raises(self):
        # table 6-6: at least one covariance data line is required
        with pytest.raises(pydantic.ValidationError):
            OCM.CovarianceTimeHistory(data_lines=[])

    def test_minimal_construction_uses_defaults(self):
        # cov_ref_frame/cov_type/cov_ordering all have spec defaults
        cov = OCM.CovarianceTimeHistory(data_lines=["2020-001T00:00:00 1e-6"])
        assert cov.data_lines == ["2020-001T00:00:00 1e-6"]

    def test_decreasing_time_raises(self):
        # Shares _check_data_lines_ordered with TrajectoryStateTimeHistory (§6.2.7.6/6.2.2.4)
        with pytest.raises(pydantic.ValidationError):
            OCM.CovarianceTimeHistory(
                data_lines=[
                    "2020-001T00:10:00 1e-6",
                    "2020-001T00:00:00 1e-6",  # decreasing
                ]
            )

    def test_duplicate_time_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.CovarianceTimeHistory(
                data_lines=[
                    "2020-001T00:00:00 1e-6",
                    "2020-001T00:00:00 1e-6",  # duplicate epoch
                ]
            )

    def test_cov_scale_min_greater_than_max_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.CovarianceTimeHistory(
                cov_scale_min=2.0,
                cov_scale_max=1.0,
                data_lines=["2020-001T00:00:00 1e-6"],
            )


class TestOCMManeuverSpecification:
    _KW: ClassVar[dict[str, str]] = {
        "man_id": "M001",
        "man_device_id": "THR1",
        "man_ref_frame": "RSW",
        "dc_type": "CONTINUOUS",
        "man_composition": "TIME_ABSOLUTE,MAN_DURA,THR_X,THR_Y,THR_Z",
    }

    def test_missing_man_id_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.ManeuverSpecification(
                **{k: v for k, v in self._KW.items() if k != "man_id"},
                data_lines=["2020-001T00:00:00 60.0 0.0 0.001 0.0"],
            )

    def test_minimal_construction_accepted(self):
        man = OCM.ManeuverSpecification(
            **self._KW,
            data_lines=["2020-001T00:00:00 60.0 0.0 0.001 0.0"],
        )
        assert man.man_id == "M001"

    def test_duplicate_time_tag_raises(self):
        # Uses _check_no_duplicate_time_tags (§6.2.8), not the strict-ordering
        # check used by trajectory/covariance blocks.
        with pytest.raises(pydantic.ValidationError):
            OCM.ManeuverSpecification(
                **self._KW,
                data_lines=[
                    "2020-001T00:00:00 60.0 0.0 0.001 0.0",
                    "2020-001T00:00:00 60.0 0.0 0.001 0.0",
                ],
            )

    def test_decreasing_time_without_duplicate_accepted(self):
        # Unlike trajectory/covariance, maneuver blocks don't require strict ordering.
        man = OCM.ManeuverSpecification(
            **self._KW,
            data_lines=[
                "2020-001T00:10:00 60.0 0.0 0.001 0.0",
                "2020-001T00:00:00 60.0 0.0 0.001 0.0",
            ],
        )
        assert len(man.data_lines) == 2


class TestOCMPerturbationsSpecification:
    def test_all_fields_optional_empty_construction_accepted(self):
        pert = OCM.PerturbationsSpecification()
        assert pert.atmospheric_model is None

    def test_with_fields_accepted(self):
        pert = OCM.PerturbationsSpecification(atmospheric_model="NRLMSISE00")
        assert pert.atmospheric_model == "NRLMSISE00"


class TestOCMOrbitDeterminationData:
    def test_missing_od_id_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.OrbitDeterminationData(od_method="RANGE", od_epoch="2020-001T00:00:00")

    def test_minimal_construction_accepted(self):
        od = OCM.OrbitDeterminationData(
            od_id="OD1", od_method="RANGE", od_epoch="2020-001T00:00:00"
        )
        assert od.od_id == "OD1"


class TestOCMUserDefinedParameters:
    def test_minimal_construction_accepted(self):
        udp = OCM.UserDefinedParameters(user_defined={"EARTH_MODEL": "WGS-84"})
        assert udp.user_defined["EARTH_MODEL"] == "WGS-84"


# ---------------------------------------------------------------------------
# Spec fixture round-trips (Annex G15-G19, KVN — should pass)
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("name", _OCM_KVN_SPEC_FIXTURES_PASSING)
def test_ocm_kvn_spec_fixture_round_trip(name: str, tmp_path: Path) -> None:
    """Read spec fixture → write → semantic-diff → re-read. (CCSDS 502.0-B-3 Annex G)"""
    fixture = FIXTURES / name
    assert fixture.exists(), f"Fixture not found: {fixture}"
    model_a = read(fixture, fmt="kvn", message_type="ocm")
    out = tmp_path / name
    write(model_a, out)
    assert_semantic_equal(fixture, out, "kvn")
    model_b = read(out, fmt="kvn", message_type="ocm")
    assert_models_equal(model_a, model_b)


@pytest.mark.parametrize("name", _OCM_KVN_SPEC_FIXTURES_WRITER_GAP)
def test_ocm_kvn_spec_fixture_round_trip_writer_gap(name: str, tmp_path: Path) -> None:
    """Placeholder: all g16-g19 writer gaps are now closed (list is empty)."""
    fixture = FIXTURES / name
    assert fixture.exists(), f"Fixture not found: {fixture}"
    model_a = read(fixture, fmt="kvn", message_type="ocm")
    out = tmp_path / name
    write(model_a, out)
    assert_semantic_equal(fixture, out, "kvn")
    model_b = read(out, fmt="kvn", message_type="ocm")
    assert_models_equal(model_a, model_b)


# ---------------------------------------------------------------------------
# OCM fixture readability — distinct from round-trip tests above
#
# These tests assert only that fixtures can be *read* and that write→read
# produces a semantically equal model.  They do NOT assert that the writer
# output matches the original file (that is the xfail round-trip concern).
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("name", _OCM_KVN_SPEC_FIXTURES_WRITER_GAP)
def test_ocm_kvn_spec_fixture_can_be_read(name: str) -> None:
    """
    OCM spec fixtures G16-G19 must be parseable without error.

    These contain physical properties, deployments, multi-trajectory blocks,
    and covariance histories — all sections the reader must handle.
    """
    fixture = FIXTURES / name
    assert fixture.exists(), f"Fixture not found: {fixture}"
    model = read(fixture, fmt="kvn", message_type="ocm")
    assert model is not None
    assert model.header is not None
    assert model.metadata is not None


@pytest.mark.parametrize("name", _OCM_KVN_SPEC_FIXTURES_WRITER_GAP)
def test_ocm_kvn_spec_fixture_re_read_preserves_model(name: str, tmp_path: Path) -> None:
    """
    Read G16-G19 fixture → write → re-read must yield an equal model.

    A failure here means the writer silently drops or corrupts fields that
    the reader parsed, which is a distinct bug from the semantic-diff failure
    already captured by test_ocm_kvn_spec_fixture_round_trip_writer_gap.
    """
    fixture = FIXTURES / name
    model_a = read(fixture, fmt="kvn", message_type="ocm")
    out = tmp_path / name
    write(model_a, out)
    model_b = read(out, fmt="kvn", message_type="ocm")
    assert_models_equal(model_a, model_b)


@pytest.mark.xfail(reason="OCM XML reader not yet exercised in CI fixtures", strict=True)
def test_ocm_xml_spec_fixture_g20(tmp_path: Path) -> None:
    fixture = FIXTURES / "ocm_g20.xml"
    model_a = read(fixture, fmt="xml", message_type="ocm")
    out = tmp_path / "ocm_g20.xml"
    write(model_a, out, fmt="xml")
    assert_semantic_equal(fixture, out, "xml")


@pytest.mark.xfail(reason="NDM combined format not supported", strict=False)
def test_ndm_g21_combined_omm_round_trip(tmp_path: Path) -> None:
    fixture = FIXTURES / "ndm_g21_combined_omm.xml"
    model_a = read(fixture, fmt="xml", message_type="omm")
    out = tmp_path / "ndm_g21.xml"
    write(model_a, out, fmt="xml")


@pytest.mark.xfail(reason="NDM combined format not supported", strict=False)
def test_ndm_g22_combined_all_round_trip(tmp_path: Path) -> None:
    fixture = FIXTURES / "ndm_g22_combined_all.xml"
    read(fixture)


# ---------------------------------------------------------------------------
# KVN round-trips (programmatic)
# ---------------------------------------------------------------------------


class TestOCMKVNRoundTrip:
    def test_minimal_header_metadata(self, tmp_path: Path) -> None:
        """Minimal OCM (header + metadata only) round-trips correctly."""
        ocm = make_ocm()
        path = tmp_path / "test.ocm"
        write(ocm, path)
        back = read(path, message_type="ocm")
        assert back.header.ccsds_ocm_vers == ocm.header.ccsds_ocm_vers
        assert back.metadata.time_system == ocm.metadata.time_system
        assert back.metadata.epoch_tzero == ocm.metadata.epoch_tzero

    def test_with_trajectory_block(self, tmp_path: Path) -> None:
        """OCM with one trajectory block round-trips."""
        ocm = OCM(
            header=OCM.Header(
                ccsds_ocm_vers="3.0", creation_date=CREATION_DATE, originator="TEST"
            ),
            metadata=OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH),
            trajectory_states=[
                OCM.TrajectoryStateTimeHistory(
                    traj_type="CARTPV",
                    traj_id="PLAN_A",
                    data_lines=[
                        "2020-001T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0",
                        "2020-001T00:10:00 6990.0 0.0 0.0 0.0 7.5 0.0",
                    ],
                )
            ],
        )
        path = tmp_path / "test.ocm"
        write(ocm, path)
        back = read(path, message_type="ocm")
        assert back.trajectory_states is not None
        assert len(back.trajectory_states) == 1
        assert back.trajectory_states[0].traj_id == "PLAN_A"

    def test_multi_traj_blocks(self, tmp_path: Path) -> None:
        """OCM with two trajectory blocks (G-18 pattern)."""
        ocm = OCM(
            header=OCM.Header(
                ccsds_ocm_vers="3.0", creation_date=CREATION_DATE, originator="TEST"
            ),
            metadata=OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH),
            trajectory_states=[
                OCM.TrajectoryStateTimeHistory(
                    traj_type="CARTPV",
                    traj_id="PLAN_A",
                    data_lines=["2020-001T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0"],
                ),
                OCM.TrajectoryStateTimeHistory(
                    traj_type="CARTPV",
                    traj_id="PLAN_B",
                    data_lines=["2020-001T01:00:00 6990.0 0.0 0.0 0.0 7.5 0.0"],
                ),
            ],
        )
        path = tmp_path / "test.ocm"
        write(ocm, path)
        back = read(path, message_type="ocm")
        assert back.trajectory_states is not None
        assert len(back.trajectory_states) == 2
        assert back.trajectory_states[1].traj_id == "PLAN_B"

    def test_idempotent(self, tmp_path: Path) -> None:
        """Write → read → write produces identical KVN output."""
        ocm = make_ocm()
        first = _OCM_WRITER.write_string(ocm)
        second = _OCM_WRITER.write_string(_OCM_READER.read_string(first))
        assert first == second


# ---------------------------------------------------------------------------
# XML round-trips
# ---------------------------------------------------------------------------


class TestOCMXMLRoundTrip:
    def test_minimal(self, tmp_path: Path) -> None:
        """Minimal OCM XML round-trip."""
        ocm = make_ocm()
        path = tmp_path / "test.xml"
        write(ocm, path, fmt="xml")
        back = read(path, fmt="xml", message_type="ocm")
        assert back.header.originator == ocm.header.originator
