"""
OCM model-validation and builder unit tests.

Covers header/metadata/data-block construction, pydantic validation errors,
and the OCMBuilder setters (no serialization).
"""

from __future__ import annotations

from typing import ClassVar

import pydantic
import pytest
from conftest import CREATION_DATE
from conftest import EPOCH
from conftest import make_ocm

from ccsds_data_messages import OCM
from ccsds_data_messages.models.values import CenterName
from ccsds_data_messages.models.values import ManeuverBasis
from ccsds_data_messages.models.values import ManeuverPurpose
from ccsds_data_messages.models.values import TimeSystem

# ---------------------------------------------------------------------------
# Model validation
# ---------------------------------------------------------------------------


class TestOCMHeader:
    def test_ocm_header_version_mandatory(self):
        # Section 7.9.1: CCSDS_OCM_VERS M
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(creation_date=CREATION_DATE, originator="TEST")

    def test_ocm_header_version_xy_pattern_required(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(ccsds_ocm_vers="3", creation_date=CREATION_DATE, originator="TEST")

    def test_ocm_header_creation_date_mandatory(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(ccsds_ocm_vers="3.0", originator="TEST")

    def test_ocm_header_originator_mandatory(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(ccsds_ocm_vers="3.0", creation_date=CREATION_DATE)

    def test_ocm_header_comment_empty_list_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(
                ccsds_ocm_vers="3.0",
                creation_date=CREATION_DATE,
                originator="TEST",
                comment=[],
            )

    def test_ocm_header_comment_accepted(self):
        h = OCM.Header(
            ccsds_ocm_vers="3.0",
            creation_date=CREATION_DATE,
            originator="TEST",
            comment=["OCM generated by mission planning system"],
        )
        assert h.comment == ["OCM generated by mission planning system"]

    def test_ocm_header_minimal_valid(self):
        h = OCM.Header(
            ccsds_ocm_vers="3.0", creation_date=CREATION_DATE, originator="TEST"
        )
        assert h.originator == "TEST"


class TestOCMMetadata:
    def test_ocm_metadata_time_system_defaults_to_utc(self):
        # TIME_SYSTEM defaults to UTC (not mandatory in model, but M in spec with UTC default)
        meta = OCM.Metadata(epoch_tzero=EPOCH)
        assert meta.time_system == TimeSystem.UTC

    def test_ocm_metadata_epoch_tzero_mandatory(self):
        # Section 6.2.2.2: EPOCH_TZERO M - no default
        with pytest.raises(pydantic.ValidationError):
            OCM.Metadata(time_system=TimeSystem.UTC)

    def test_ocm_metadata_time_system_utc_accepted(self):
        meta = OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
        assert meta.time_system == TimeSystem.UTC

    def test_ocm_metadata_epoch_tzero_calendar_format_accepted(self):
        meta = OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero="2020-01-01T00:00:00")
        assert meta.epoch_tzero is not None

    def test_ocm_metadata_epoch_tzero_doy_format_accepted(self):
        meta = OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero="2020-001T00:00:00")
        assert meta.epoch_tzero is not None

    def test_ocm_metadata_julian_date_epoch_tzero_rejected(self):
        # epoch_tzero is absolute-only (CCSDSDate); section 7.5.10 defines only the
        # calendar and day-of-year formats, so a bare decimal is rejected.
        with pytest.raises(pydantic.ValidationError):
            OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero="2459945.5")

    def test_ocm_metadata_optional_fields_default_none(self):
        meta = OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
        assert meta.object_name is None
        assert meta.international_designator is None

    def test_ocm_metadata_object_name_accepted(self):
        meta = OCM.Metadata(
            time_system=TimeSystem.UTC, epoch_tzero=EPOCH, object_name="TESTSAT"
        )
        assert meta.object_name == "TESTSAT"


class TestOCMTopLevel:
    def test_ocm_minimal_construction(self):
        ocm = make_ocm()
        assert ocm.header.ccsds_ocm_vers == "3.0"
        assert ocm.metadata.time_system == TimeSystem.UTC

    def test_ocm_with_trajectory_block(self):
        # OCM can have optional trajectory state time history blocks
        ocm = make_ocm()
        assert ocm.header.originator == "JAXA"

    def test_ocm_header_plus_metadata_only_accepted(self):
        # Section 6.2: header + metadata are the minimum; all data blocks are optional
        ocm = OCM(
            header=OCM.Header(
                ccsds_ocm_vers="3.0", creation_date=CREATION_DATE, originator="JAXA"
            ),
            metadata=OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH),
        )
        assert ocm.metadata.epoch_tzero is not None

    def test_ocm_header_version_3_5_accepted_as_valid_minor_increment(self):
        # Section 7.9.1: OCM supports any minor version under major 3
        h = OCM.Header(
            ccsds_ocm_vers="3.5", creation_date=CREATION_DATE, originator="TEST"
        )
        assert h.ccsds_ocm_vers == "3.5"

    def test_ocm_header_version_4_0_raises_non_3_major(self):
        # Section 7.9.1: OCM major version must be 3; '4.0' is not valid
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(
                ccsds_ocm_vers="4.0", creation_date=CREATION_DATE, originator="TEST"
            )

    def test_ocm_header_version_2_0_raises_non_3_major(self):
        # Section 7.9.1: OCM major version must be 3; '2.0' is not valid
        with pytest.raises(pydantic.ValidationError):
            OCM.Header(
                ccsds_ocm_vers="2.0", creation_date=CREATION_DATE, originator="TEST"
            )


class TestOCMTrajectoryState:
    def test_ocm_trajectory_state_data_lines_strictly_increasing(self):
        # Section 6.2.2.5: time tags must be strictly increasing within a block
        with pytest.raises(pydantic.ValidationError):
            OCM.TrajectoryStateTimeHistory(
                traj_type="CARTPV",
                traj_id="PLAN_A",
                data_lines=[
                    "2020-001T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0",
                    "2020-001T00:00:00 6990.0 0.0 0.0 0.0 7.5 0.0",  # duplicate epoch
                ],
            )

    def test_ocm_trajectory_state_decreasing_time_raises(self):
        # Section 6.2.2.4: duplicate time tag forbidden
        with pytest.raises(pydantic.ValidationError):
            OCM.TrajectoryStateTimeHistory(
                traj_type="CARTPV",
                traj_id="PLAN_A",
                data_lines=[
                    "2020-001T00:10:00 7000.0 0.0 0.0 0.0 7.5 0.0",
                    "2020-001T00:00:00 6990.0 0.0 0.0 0.0 7.5 0.0",  # decreasing
                ],
            )

    def test_ocm_trajectory_state_single_data_line_accepted(self):
        # Single-line blocks are valid (no ordering constraint needed)
        block = OCM.TrajectoryStateTimeHistory(
            traj_type="CARTPV",
            traj_id="PLAN_A",
            data_lines=["2020-001T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0"],
        )
        assert len(block.data_lines) == 1

    def test_ocm_trajectory_state_increasing_time_accepted(self):
        block = OCM.TrajectoryStateTimeHistory(
            traj_type="CARTPV",
            traj_id="PLAN_A",
            data_lines=[
                "2020-001T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0",
                "2020-001T00:10:00 6990.0 0.0 0.0 0.0 7.5 0.0",
                "2020-001T00:20:00 6980.0 0.0 0.0 0.0 7.5 0.0",
            ],
        )
        assert len(block.data_lines) == 3

    def test_ocm_trajectory_empty_data_lines_raises(self):
        # Section 6.2.2.5: an empty data block has no meaning
        with pytest.raises(pydantic.ValidationError):
            OCM.TrajectoryStateTimeHistory(
                traj_type="CARTPV",
                traj_id="PLAN_A",
                data_lines=[],
            )

    def test_ocm_trajectory_mixed_absolute_and_relative_tags_raises(self):
        # Section 6.2.2.5: a block established as absolute-tagged must not accept a
        # stray relative-format tag.
        with pytest.raises(pydantic.ValidationError, match=r"section 6\.2\.2\.5"):
            OCM.TrajectoryStateTimeHistory(
                traj_type="CARTPV",
                traj_id="PLAN_A",
                data_lines=[
                    "2020-001T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0",
                    "120.5 6990.0 0.0 0.0 0.0 7.5 0.0",
                ],
            )

    def test_ocm_covariance_mixed_absolute_and_relative_tags_raises(self):
        # Same section 6.2.2.5 check applies to covariance blocks via the same helper.
        with pytest.raises(pydantic.ValidationError, match=r"section 6\.2\.2\.5"):
            OCM.CovarianceTimeHistory(
                data_lines=[
                    "2020-001T00:00:00 1e-6",
                    "120.5 1e-6",
                ]
            )


# ---------------------------------------------------------------------------
# OCMBuilder - one case per setter method
# ---------------------------------------------------------------------------


class TestOCMBuilder:
    def test_build_minimal(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .build()
        )
        assert ocm.header.originator == "JAXA"
        assert ocm.metadata.time_system == TimeSystem.UTC

    def test_build_with_trajectory_state(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .add_trajectory(
                traj_type="CARTPV",
                traj_id="PLAN_A",
                data_lines=["2020-001T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0"],
            )
            .build()
        )
        assert ocm.trajectory_states is not None
        assert ocm.trajectory_states[0].traj_id == "PLAN_A"

    def test_build_with_physical_characteristics(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .physical_characteristics(wet_mass=1000.0)
            .build()
        )
        assert ocm.physical_characteristics is not None
        assert ocm.physical_characteristics.wet_mass == 1000.0

    def test_build_with_covariance(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .add_covariance(
                cov_ref_frame="RSW",
                cov_type="CARTPV",
                cov_ordering="LTM",
                data_lines=["2020-001T00:00:00 1e-6"],
            )
            .build()
        )
        assert ocm.covariances is not None
        assert ocm.covariances[0].cov_ref_frame == "RSW"

    def test_build_with_maneuver(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .add_maneuver(
                man_id="M001",
                man_device_id="THR1",
                man_ref_frame="RSW",
                dc_type="CONTINUOUS",
                man_composition="TIME_ABSOLUTE,MAN_DURA,THR_X,THR_Y,THR_Z",
                data_lines=[_prop_row()],
            )
            .build()
        )
        assert ocm.maneuvers is not None
        assert ocm.maneuvers[0].man_id == "M001"

    def test_build_with_perturbations_and_orbit_determination(self):
        # orbit_determination() requires a perturbations block to also be set.
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .perturbations(atmospheric_model="NRLMSISE00")
            .orbit_determination(
                od_id="OD1", od_method="RANGE", od_epoch="2020-001T00:00:00"
            )
            .build()
        )
        assert ocm.perturbations is not None
        assert ocm.orbit_determination is not None
        assert ocm.orbit_determination.od_id == "OD1"

    def test_build_with_user_defined(self):
        ocm = (
            OCM.builder()
            .header(originator="JAXA", creation_date=CREATION_DATE)
            .metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH)
            .user_defined(EARTH_MODEL="WGS-84")
            .build()
        )
        assert ocm.user_defined is not None
        assert ocm.user_defined.user_defined["EARTH_MODEL"] == "WGS-84"

    def test_build_without_metadata_raises(self):
        with pytest.raises(ValueError):
            OCM.builder().header(originator="JAXA", creation_date=CREATION_DATE).build()


# ---------------------------------------------------------------------------
# Remaining OCM block types - direct-construction validation
# ---------------------------------------------------------------------------


class TestOCMSpaceObjectPhysicalCharacteristics:
    def test_all_fields_optional_empty_construction_accepted(self):
        phys = OCM.SpaceObjectPhysicalCharacteristics()
        assert phys.wet_mass is None

    def test_with_fields_accepted(self):
        phys = OCM.SpaceObjectPhysicalCharacteristics(wet_mass=1000.0, dry_mass=800.0)
        assert phys.wet_mass == 1000.0
        assert phys.dry_mass == 800.0


class TestOCMCovarianceTimeHistory:
    def test_empty_data_lines_raises(self):
        # table 6-6: at least one covariance data line is required
        with pytest.raises(pydantic.ValidationError):
            OCM.CovarianceTimeHistory(data_lines=[])

    def test_minimal_construction_uses_defaults(self):
        # cov_ref_frame/cov_type/cov_ordering all have spec defaults
        cov = OCM.CovarianceTimeHistory(data_lines=["2020-001T00:00:00 1e-6"])
        assert cov.data_lines == ["2020-001T00:00:00 1e-6"]

    def test_decreasing_time_raises(self):
        # Shares _check_data_lines_ordered with TrajectoryStateTimeHistory (section 6.2.7.6/6.2.2.4)
        with pytest.raises(pydantic.ValidationError):
            OCM.CovarianceTimeHistory(
                data_lines=[
                    "2020-001T00:10:00 1e-6",
                    "2020-001T00:00:00 1e-6",  # decreasing
                ]
            )

    def test_duplicate_time_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.CovarianceTimeHistory(
                data_lines=[
                    "2020-001T00:00:00 1e-6",
                    "2020-001T00:00:00 1e-6",  # duplicate epoch
                ]
            )

    def test_cov_scale_min_greater_than_max_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.CovarianceTimeHistory(
                cov_scale_min=2.0,
                cov_scale_max=1.0,
                data_lines=["2020-001T00:00:00 1e-6"],
            )


_ManLine = OCM.ManeuverSpecification.ManeuverDataLine
_DeployLine = OCM.ManeuverSpecification.DeploymentDataLine


def _prop_row(time_tag: str = "2020-001T00:00:00") -> _ManLine:
    """A propulsive maneuver row matching the TIME_ABSOLUTE,MAN_DURA,THR_X/Y/Z KW."""
    return _ManLine(time_tag=time_tag, man_dura=60.0, thr_x=0.0, thr_y=0.001, thr_z=0.0)


class TestOCMManeuverSpecification:
    _KW: ClassVar[dict[str, str]] = {
        "man_id": "M001",
        "man_device_id": "THR1",
        "man_ref_frame": "RSW",
        "dc_type": "CONTINUOUS",
        "man_composition": "TIME_ABSOLUTE,MAN_DURA,THR_X,THR_Y,THR_Z",
    }

    def test_missing_man_id_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.ManeuverSpecification(
                **{k: v for k, v in self._KW.items() if k != "man_id"},
                data_lines=[_prop_row()],
            )

    def test_minimal_construction_accepted(self):
        man = OCM.ManeuverSpecification(**self._KW, data_lines=[_prop_row()])
        assert man.man_id == "M001"

    def test_duplicate_time_tag_raises(self):
        # Uses _check_no_duplicate_time_tags (section 6.2.8), not the strict-ordering
        # check used by trajectory/covariance blocks.
        with pytest.raises(pydantic.ValidationError):
            OCM.ManeuverSpecification(**self._KW, data_lines=[_prop_row(), _prop_row()])

    def test_decreasing_time_without_duplicate_accepted(self):
        # Unlike trajectory/covariance, maneuver blocks don't require strict ordering.
        man = OCM.ManeuverSpecification(
            **self._KW,
            data_lines=[_prop_row("2020-001T00:10:00"), _prop_row("2020-001T00:00:00")],
        )
        assert len(man.data_lines) == 2

    def test_man_purpose_accepts_known_enum_value(self):
        man = OCM.ManeuverSpecification(
            **self._KW, man_purpose=ManeuverPurpose.SK, data_lines=[_prop_row()]
        )
        assert man.man_purpose == ManeuverPurpose.SK

    def test_man_purpose_accepts_grav_assist_parametric_value(self):
        purpose = ManeuverPurpose.grav_assist_from(CenterName.EARTH)
        man = OCM.ManeuverSpecification(
            **self._KW, man_purpose=purpose, data_lines=[_prop_row()]
        )
        assert man.man_purpose == "GRAV_ASSIST_FROM_EARTH"

    def test_man_purpose_accepts_arbitrary_free_text(self):
        # Table 6-7's vocabulary is "could include", not a closed set.
        man = OCM.ManeuverSpecification(
            **self._KW, man_purpose="CUSTOM_PURPOSE", data_lines=[_prop_row()]
        )
        assert man.man_purpose == "CUSTOM_PURPOSE"

    def test_typed_row_exposes_named_columns(self):
        man = OCM.ManeuverSpecification(**self._KW, data_lines=[_prop_row()])
        row = man.data_lines[0]
        assert isinstance(row, _ManLine)
        assert row.man_dura == 60.0
        assert row.thr_y == pytest.approx(0.001)

    def test_thr_interp_invalid_value_raises(self):
        # Table 6-8: THR_INTERP values shall be 'ON' or 'OFF'.
        with pytest.raises(pydantic.ValidationError):
            _ManLine(time_tag="2020-001T00:00:00", thr_interp="MAYBE")

    def test_deploy_mass_positive_raises(self):
        # Table 6-9: DEPLOY_MASS is a host-mass decrement and shall be <= 0.0.
        with pytest.raises(pydantic.ValidationError):
            _DeployLine(time_tag="0.0", deploy_mass=1.0)

    def test_row_type_mismatched_to_composition_raises(self):
        # Propulsive composition must take ManeuverDataLine rows (6.2.8.15).
        with pytest.raises(pydantic.ValidationError):
            OCM.ManeuverSpecification(
                **self._KW,
                data_lines=[_DeployLine(time_tag="0.0", deploy_mass=-1.0)],
            )

    def test_man_units_count_after_time_tag_accepted(self):
        # 4 units == elements after the time tag (table 6-7 normative text).
        man = OCM.ManeuverSpecification(
            **self._KW, man_units="[s, N, N, N]", data_lines=[_prop_row()]
        )
        assert man.man_units == "[s, N, N, N]"

    def test_man_units_count_with_leading_time_unit_accepted(self):
        # 5 units == full composition (leading n/a for the time tag), the form
        # used by the CCSDS Annex G page-206 example and the ocm_g17 fixture.
        man = OCM.ManeuverSpecification(
            **self._KW, man_units="[n/a, s, N, N, N]", data_lines=[_prop_row()]
        )
        assert man.man_units == "[n/a, s, N, N, N]"

    def test_man_units_wrong_count_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.ManeuverSpecification(
                **self._KW,
                man_units="[s, N]",  # 2 units, need 4 or 5
                data_lines=[_prop_row()],
            )

    # DC vector format (section 7.6.1) and execution-window ordering (table 6-7).

    def test_dc_ref_dir_three_numeric_components_accepted(self):
        man = OCM.ManeuverSpecification(
            **self._KW, dc_ref_dir="1.0 0.0 0.0", data_lines=[_prop_row()]
        )
        assert man.dc_ref_dir == "1.0 0.0 0.0"

    def test_dc_ref_dir_wrong_component_count_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.ManeuverSpecification(
                **self._KW, dc_ref_dir="1.0 0.0", data_lines=[_prop_row()]
            )

    def test_dc_ref_dir_non_numeric_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.ManeuverSpecification(
                **self._KW, dc_ref_dir="1.0 UP 0.0", data_lines=[_prop_row()]
            )

    def test_dc_body_trigger_numeric_vector_accepted(self):
        man = OCM.ManeuverSpecification(
            **self._KW, dc_body_trigger="0.0 0.0 1.0", data_lines=[_prop_row()]
        )
        assert man.dc_body_trigger == "0.0 0.0 1.0"

    def test_dc_exec_start_before_win_open_raises(self):
        # Both relative (seconds): exec 10 < window open 50 violates table 6-7.
        with pytest.raises(pydantic.ValidationError):
            OCM.ManeuverSpecification(
                **self._KW,
                dc_win_open="50.0",
                dc_exec_start="10.0",
                data_lines=[_prop_row()],
            )

    def test_dc_exec_stop_after_win_close_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.ManeuverSpecification(
                **self._KW,
                dc_win_close="100.0",
                dc_exec_stop="150.0",
                data_lines=[_prop_row()],
            )

    def test_dc_execution_within_window_accepted(self):
        man = OCM.ManeuverSpecification(
            **self._KW,
            dc_win_open="0.0",
            dc_win_close="100.0",
            dc_exec_start="10.0",
            dc_exec_stop="90.0",
            data_lines=[_prop_row()],
        )
        assert man.dc_exec_start == "10.0"

    def test_dc_mixed_format_window_not_compared(self):
        # Relative exec vs absolute window can't be ordered without EPOCH_TZERO,
        # so the block-level check abstains (no false rejection).
        man = OCM.ManeuverSpecification(
            **self._KW,
            dc_win_open="2020-001T00:00:00",
            dc_exec_start="10.0",
            data_lines=[_prop_row()],
        )
        assert man.dc_exec_start == "10.0"


class TestOCMManeuverDCWindowsAcrossFormats:
    """
    OCM-level DC window ordering when exec/window tags mix relative and absolute.

    Same-format pairs are ordered inside ManeuverSpecification; a relative tag
    paired with an absolute one is resolved against EPOCH_TZERO at the OCM level
    (table 6-7: DC_EXEC_START >= DC_WIN_OPEN, DC_EXEC_STOP <= DC_WIN_CLOSE).
    """

    # EPOCH_TZERO defaults to "2020-001T00:00:00" via make_ocm, so relative second
    # offsets resolve against midnight on day 001.
    @staticmethod
    def _maneuver(**dc_kw: str) -> OCM.ManeuverSpecification:
        return OCM.ManeuverSpecification(
            man_id="M1",
            man_device_id="THR1",
            man_ref_frame="RSW",
            dc_type="CONTINUOUS",
            man_composition="TIME_ABSOLUTE,MAN_DURA,THR_X,THR_Y,THR_Z",
            data_lines=[_prop_row()],
            **dc_kw,
        )

    def _ocm(self, man: OCM.ManeuverSpecification) -> OCM:
        # Build via the constructor (not model_copy) so model validators run.
        return OCM(
            header=OCM.Header(
                ccsds_ocm_vers="3.0", creation_date=CREATION_DATE, originator="JAXA"
            ),
            metadata=OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH),
            maneuvers=[man],
        )

    def test_mixed_format_exec_start_before_window_open_raises(self):
        # exec_start absolute 00:00:50 (=50 s) < win_open relative 100 s, which is a violation.
        man = self._maneuver(dc_win_open="100.0", dc_exec_start="2020-001T00:00:50")
        with pytest.raises(pydantic.ValidationError):
            self._ocm(man)

    def test_mixed_format_exec_stop_after_window_close_raises(self):
        # exec_stop absolute 00:02:00 (=120 s) > win_close relative 100 s, which is a violation.
        man = self._maneuver(dc_win_close="100.0", dc_exec_stop="2020-001T00:02:00")
        with pytest.raises(pydantic.ValidationError):
            self._ocm(man)

    def test_mixed_format_execution_within_window_accepted(self):
        man = self._maneuver(
            dc_win_open="100.0",
            dc_exec_start="2020-001T00:02:00",  # 120 s >= 100 s
        )
        ocm = self._ocm(man)
        assert ocm.maneuvers is not None

    def test_maneuver_alone_does_not_order_mixed_pair(self):
        # Standalone (no EPOCH_TZERO context) the block abstains on mixed formats.
        man = self._maneuver(dc_win_open="100.0", dc_exec_start="2020-001T00:00:50")
        assert man.dc_exec_start == "2020-001T00:00:50"


class TestOCMPerturbationsSpecification:
    def test_all_fields_optional_empty_construction_accepted(self):
        pert = OCM.PerturbationsSpecification()
        assert pert.atmospheric_model is None

    def test_with_fields_accepted(self):
        pert = OCM.PerturbationsSpecification(atmospheric_model="NRLMSISE00")
        assert pert.atmospheric_model == "NRLMSISE00"


class TestOCMOrbitDeterminationData:
    def test_missing_od_id_raises(self):
        with pytest.raises(pydantic.ValidationError):
            OCM.OrbitDeterminationData(od_method="RANGE", od_epoch="2020-001T00:00:00")

    def test_minimal_construction_accepted(self):
        od = OCM.OrbitDeterminationData(
            od_id="OD1", od_method="RANGE", od_epoch="2020-001T00:00:00"
        )
        assert od.od_id == "OD1"

    def test_seven_digit_relative_od_epoch_accepted(self):
        # od_epoch is a TimeTag (section 6.2.2.3): a relative time in seconds is valid
        # regardless of its digit count, e.g. ~28.5 days after EPOCH_TZERO.
        od = OCM.OrbitDeterminationData(
            od_id="OD1", od_method="RANGE", od_epoch="2459945.5"
        )
        assert od.od_epoch == "2459945.5"


class TestOCMUserDefinedParameters:
    def test_minimal_construction_accepted(self):
        udp = OCM.UserDefinedParameters(user_defined={"EARTH_MODEL": "WGS-84"})
        assert udp.user_defined["EARTH_MODEL"] == "WGS-84"


class TestOCMCompositeManeuverGroups:
    """composite_maneuver_groups groups constituents by MAN_ID/BASIS/REF_FRAME (section 6.2.8.11)."""

    @staticmethod
    def _man(
        man_id: str,
        man_ref_frame: str = "RSW",
        man_basis: ManeuverBasis = ManeuverBasis.PLANNED,
    ) -> OCM.ManeuverSpecification:
        return OCM.ManeuverSpecification(
            man_id=man_id,
            man_device_id="THR1",
            man_ref_frame=man_ref_frame,
            man_basis=man_basis,
            dc_type="CONTINUOUS",
            man_composition="TIME_ABSOLUTE,MAN_DURA,THR_X,THR_Y,THR_Z",
            data_lines=[_prop_row()],
        )

    @staticmethod
    def _ocm(maneuvers: list[OCM.ManeuverSpecification]) -> OCM:
        return OCM(
            header=OCM.Header(
                ccsds_ocm_vers="3.0", creation_date=CREATION_DATE, originator="JAXA"
            ),
            metadata=OCM.Metadata(time_system=TimeSystem.UTC, epoch_tzero=EPOCH),
            maneuvers=maneuvers,
        )

    def test_groups_constituents_sharing_id_basis_frame(self):
        ocm = self._ocm([self._man("M1"), self._man("M1"), self._man("M2")])
        groups = ocm.composite_maneuver_groups()
        assert len(groups) == 2
        assert [len(g) for g in groups] == [2, 1]
        assert {g[0].man_id for g in groups} == {"M1", "M2"}

    def test_different_ref_frame_separates_groups(self):
        ocm = self._ocm(
            [self._man("M1", man_ref_frame="RSW"), self._man("M1", man_ref_frame="TNW")]
        )
        assert len(ocm.composite_maneuver_groups()) == 2

    def test_no_maneuvers_returns_empty(self):
        assert make_ocm().composite_maneuver_groups() == []
